name: Trigger Vercel Cron

on:
  schedule:
    - cron: '* * * * *' # Runs every minute
  workflow_dispatch: # Allows you to click "Run workflow" manually to test

jobs:
  ping-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        run: |
          curl -X POST https://discord-bot-three-chi.vercel.app/api/check-contest \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"